### ISSUE TITLE
Feature request: Follow symlinks by default

### ISSUE THREAD

**Issue by mathieu-aubin** [claudiodangelis/qrcp#167] opened 2020-08-02 16:32 UTC
I'm opening this issue because:

- [x] I have found a bug (or maybe an *oversight*??)
- [x] I want to request a feature
- [x] I have a question
- [ ] Other

It would make sense to follow symlinks by default as currently, the link itself is used as file for download which result in, according to the output of `file` command after download:

`somefile.tar.gz: very short file (no magic)`

i would assume a person would not want to download/share such a file and most likely, one would logically (to me anyways) assume that the linked/target file would end up being served.

I hope this makes sense. I happenned to fall on this 'issue/behaviour' the very first time i tested the program while trying something quick.

Thanks for considering!

**Comment by mathieu-aubin** [comment] 2020-08-02 19:26
So i have tried some other stuff and it seems that...

Either this program has issues with serving already zipped files AND doesnt follow symlinks
OR... just has issue with serving zipped data

A .yml file, per example, returns correctly but a zipped file or a symlink ends up serving a "enpty" file. this the the curl output headers for a request to either a symlink or a zip file

```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sun, 02 Aug 2020 19:17:43 GMT
Content-Length: 1
```

I have tried with the current latest release and also compiling from source code and same thing.I wish i am doing something wrong and all is good. Anyways, this 'troubles' me somehow

**Comment by claudiodangelis** [comment] 2020-08-10 06:55
Thanks for pointing this out @mathieu-aubin, I never actually tried it with symlinks.

Will have a look later this week, cheers,
Claudio

**Comment by claudiodangelis** [comment] 2020-08-25 07:15
Hi @mathieu-aubin, I can't reproduce the issue, the symlinks are correctly followed and the zipped/tar.gz'd files correctly served.
Awkward question: did you try with an actual browser (desktop browsers are fine too)?
You may be hitting this if-clause: https://github.com/claudiodangelis/qrcp/blob/master/server/server.go#L139

```golang
	http.HandleFunc("/send/"+path, func(w http.ResponseWriter, r *http.Request) {
		if cookie.Value == "" {
			if !strings.HasPrefix(r.Header.Get("User-Agent"), "Mozilla") {
				http.Error(w, "", http.StatusOK)
				return
			}
```

This was implemented to support multiple requests coming from the same browser session (i.e.: chunks being downloaded in parallel), though I realize it may be useful to have curl support too.

Please let me know if it works OK from the browser and in case please feel free to close this issue, I will an issue to track to work to be done to support curl and other http clients soon.

Cheers,
Claudio

**Comment by claudiodangelis** [comment] 2020-09-03 11:00
I will close this ticket now. FYI, the curl support is being added as per https://github.com/claudiodangelis/qrcp/pull/175 

Thanks!
Claudio

**Closed by claudiodangelis** 2020-09-03 11:00 UTC
