### ISSUE TITLE
QR code doesn't properly render on Windows

### ISSUE THREAD

**Issue by jianboy** [claudiodangelis/qrcp#95] opened 2020-04-22 13:34 UTC
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

the qrcode is too big!!!
*When I zoom the  cmd window, the QR code disappears.*

![1](https://user-images.githubusercontent.com/11532015/79988281-0aaf7380-84e1-11ea-9f74-5c8b3c464054.gif)

![image](https://user-images.githubusercontent.com/11532015/80004655-2ae92d80-84f5-11ea-9d4d-746f679d9188.png)

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_

**Comment by claudiodangelis** [comment] 2020-04-23 07:15
Hello @jianboy, thanks for reporting! 
Please allow me some time to research why the `qrConfig.HalfBlocks = false` was introduced in the first place, and then plan a solution. 

Does it work fine for you if you set `qrConfig.HalfBlocks = true`?

Thanks,
C

**Comment by jianboy** [comment] 2020-04-23 12:38
> Hello @jianboy, thanks for reporting!
> Please allow me some time to research why the `qrConfig.HalfBlocks = false` was introduced in the first place, and then plan a solution.
> 
> Does it work fine for you if you set `qrConfig.HalfBlocks = true`?
> 
> Thanks,
> C

I set qrConfig.HalfBlocks = true , 

and qrcode is flat.

**Comment by claudiodangelis** [comment] 2020-04-24 12:30
@Lorenz11x are you having this issue in Windows?

**Comment by jianboy** [comment] 2020-04-24 13:50
it maybe cause by the bug:
https://github.com/mdp/qrterminal/issues/20

**Comment by Lorenz11x** [comment] 2020-04-26 20:52
@claudiodangelis  si, in Windows10.
Soluzione?

**Comment by claudiodangelis** [comment] 2020-04-29 14:28
We just deployed a new version, 0.6.1, which uses a different QR encoding library (props to @anoop-b :tada:). 
Can you @Lorenz11x and @jianboy please try the new version and let me know if it fixes the issue? 

Thanks,
C

**Comment by jianboy** [comment] 2020-04-29 20:05
It can not show qr correctly. May be you can open a file with a default software and not show it in cmd windows.  

![BaiduHi_2020-4-30_3-59-10](https://user-images.githubusercontent.com/11532015/80641183-0cf06f80-8a97-11ea-8640-a465d3491161.png)

**Comment by claudiodangelis** [comment] 2020-04-29 21:24
@jianboy just wondering: does it work with a monospace font?

**Comment by jianboy** [comment] 2020-04-29 21:31
> @jianboy just wondering: does it work with a monospace font?

monospace font? I didn't know how to try it.

**Comment by MasonZhangXM** [comment] 2020-04-30 00:59
it works on monospace not others,i have the same problem with poster.

**Comment by anoop-b** [comment] 2020-04-30 15:49
I can confirm that it works well in powershell on windows and cmd. But qr-code disappears after cmd window is resized.
Also works well on the new windows [terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab). I think Microsoft is addressing these underlying issues with the introduction of new terminal.

**Comment by anoop-b** [comment] 2020-04-30 15:51
Hey @jianboy , I couldn't reproduce this issue with the new build. Could you try doing a fresh install of qrpc?

**Comment by jianboy** [comment] 2020-04-30 20:55
> Hey @jianboy , I couldn't reproduce this issue with the new build. Could you try doing a fresh install of qrcp?

sure, you can see my video:

http://cdn.yoqi.me/direct/2020-05-01/Video_2020-05-01_044740.mp4

**Comment by ssxwcz** [comment] 2020-05-06 03:26
> I can confirm that it works well in powershell and cmd on windows . But qr-code disappears after cmd window is resized.
> Also works well on the new windows [terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab). I think Microsoft is addressing these underlying issues with the introduction of new terminal.

Hey, I also use Windows terminal, but the QR code cannot be displayed properly
go version go1.14.2 windows/amd64
Font: [CaskaydiaCove Nerd Font Mono](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip)
![image](https://user-images.githubusercontent.com/43665491/81131502-f1e19c00-8f7d-11ea-9da6-04513725a82c.png)
I think it should be related to the font. I can display it normally with [FuraCode Nerd Font Mono](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip)
![image](https://user-images.githubusercontent.com/43665491/81132876-7504f100-8f82-11ea-97a2-f3045a7aec4d.png)

**Comment by claudiodangelis** [comment] 2020-05-06 05:35
Thanks everyone for reporting. In my understanding, the issue with the QR in Windows is always related to the font used in terminal, either it is not monospace or line spacing is too high.

Since this is not really an issue with qrcp itself I'm considering closing this issue in a few days.

**Comment by rongzedong** [comment] 2020-06-01 06:17
run this qrcp.reg:

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe]
"CodePage"=dword:0000fde9
"FontFamily"=dword:00000036
"FontWeight"=dword:00000190
"FaceName"="Consolas"
"ScreenBufferSize"=dword:232900d2
"WindowSize"=dword:002b00d2

**Comment by claudiodangelis** [comment] 2020-06-01 06:38
Hello @rongzedong, thanks for this tip.

Is there anyone in this conversation who can successfully resolve the problem by using the specific configuration as per @rongzedong suggestion?

Thanks

**Comment by jianboy** [comment] 2020-06-02 04:51
I don't want modify registry. I tried another way. 
![1](https://user-images.githubusercontent.com/11532015/83481217-bcbe6000-a4cf-11ea-890b-297f94e495c3.gif)

**Comment by anoop-b** [comment] 2020-06-30 14:34
Can somebody on windows please test if this works ? [PR](https://github.com/claudiodangelis/qrcp/pull/163)

**Comment by claudiodangelis** [comment] 2020-09-02 17:05
Hello everyone, we released a new version, `0.6.4`, which adds the option to open the QR into a browser window:

```sh
qrcp --browser MyDocument.pdf
```

This can be useful for those running into rendering issues in the terminal.
Cheers,
Claudio

**Comment by jianboy** [comment] 2020-09-02 17:13
**I developed a software to realize this function.**

![3](https://user-images.githubusercontent.com/11532015/92014791-61c42f80-ed82-11ea-892a-65d70687de8d.gif)

**Comment by claudiodangelis** [comment] 2020-09-02 17:29
Oh that's great!

**Comment by claudiodangelis** [comment] 2020-09-02 17:30
By the way, since I'm not hearing anymore about this issue, I will close the ticket for now.

Thanks everyone!

**Closed by claudiodangelis** 2020-09-02 17:30 UTC

**Comment by yuwujin88** [comment] 2023-12-13 04:06
> **我开发了一个软件来实现这个功能。**
> 
> ![3](https://user-images.githubusercontent.com/11532015/92014791-61c42f80-ed82-11ea-892a-65d70687de8d.gif) [ ![3](https://user-images.githubusercontent.com/11532015/92014791-61c42f80-ed82-11ea-892a-65d70687de8d.gif) ](https://user-images.githubusercontent.com/11532015/92014791-61c42f80-ed82-11ea-892a-65d70687de8d.gif) [ ](https://user-images.githubusercontent.com/11532015/92014791-61c42f80-ed82-11ea-892a-65d70687de8d.gif)

请问你的QR sednto未发布吗？
