### ISSUE TITLE
Unable to open link on phone (Linux)

### ISSUE THREAD

**Issue by PFleur** [claudiodangelis/qrcp#343] opened 2024-10-31 01:55 UTC
I'm opening this issue because:
I am unable to open the link generated by `go receive` on my phone with it returning an unable to connect error. I am currently running qrcp build from current source on github and on mobile I have tried with fennec and chromium with both returning an address unreachable error.

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: _go version go1.23.1 linux/amd64_
- My GOPATH is set to: _/home/user/go/_

**Comment by claudiodangelis** [comment] 2024-10-31 15:07
Hi, does it work when you want to send files from the laptop to the mobile?

**Comment by PFleur** [comment] 2024-11-01 00:24
Apologies for the late reply, it does not.

**Comment by claudiodangelis** [comment] 2024-12-27 16:01
Hello, you must be sure of two things:
- both laptop and mobile must be on the same wifi network
- if using a firewall, make sure that it's not blocking the outgoing traffic on the port used by qrcp

If you are using linux, you can try the following:

- open the port 8080 on your firewall

```
sudo firewall-cmd --permanent --add-port 8080
sudo firewall-cmd --reload
```
- use qrcp on that port

```
qrcp -p 8080 some-file.txt
```

Remember that you can permanently configure the tool to use a specific port by adding this to the configuration file:

```
port: 8080
```

Let me know if this helps, thanks!

**Comment by claudiodangelis** [comment] 2024-12-27 16:41
I'm quite sure the problem is related to the firewall, so I will close this issue for now. Happy to investigate together if this doesn't fix it.
Thanks!
C

**Closed by claudiodangelis** 2024-12-27 16:41 UTC
