### ISSUE TITLE
Generated code does not scan reliably with Source Code Pro font

### ISSUE THREAD

**Issue by efung** [claudiodangelis/qrcp#7] opened 2018-03-22 20:35 UTC
I'm using iTerm2, with Source Code Pro as my monospaced font. The QR code doesn't scan reliably, as there's some gaps where the pattern should be continuous. Is there a Unicode char that is guaranteed to take up the entire height/width that could be used? 

![screen shot 2018-03-22 at 4 34 15 pm](https://user-images.githubusercontent.com/301094/37796958-e3480c1c-2dee-11e8-90a6-52bdbd03c4c0.png)

**Comment by sa7mon** [comment] 2018-03-22 20:49
(Side Note: ) What are your background and font colors? I like the theme.

**Comment by cIaudiodangeIis** [comment] 2018-03-23 02:02
Why don't you go and figure that out for yourself. Go away.

**Comment by bvaughn** [comment] 2018-03-23 04:37
I've reported @cIaudiodangeIis to Twitter as an abusive account.

Do not confuse this user with @claudiodangelis. Although the names look the same on GitHub.com, this is a troll account. The second letter is an upper case "i" rather than a lower case "l".

**Comment by efung** [comment] 2018-03-23 14:50
@sa7mon Background is #002833 and foreground is #b2b2b2. I installed http://ethanschoonover.com/solarized but don't remember if I further customized it.

**Comment by efung** [comment] 2018-03-23 14:52
From looking at the underlying library used to generate the QR codes (https://github.com/mdp/qrterminal/blob/master/qrterminal.go#L13-L16), there is the option to use half or full blocks.

Perhaps this could be configurable via an environment variable or an .rc file?

**Comment by claudiodangelis** [comment] 2018-03-28 09:29
I still have to look into this, will do soon hopefully, thanks for your patience!

**Comment by claudiodangelis** [comment] 2020-04-20 07:21
Hello @efung, are you still running into this issue?

**Comment by efung** [comment] 2020-04-20 13:27
I'm not doing any Android development anymore, and haven't use your tool in a while. But I believe this is likely still an issue?

**Comment by claudiodangelis** [comment] 2020-04-21 11:24
I just tried myself and could not reproduce the issue. Considering that no one else complained in the last 2 years, I'm going to close this for now.

Thanks!

**Closed by claudiodangelis** 2020-04-21 11:24 UTC
Labels: help wanted
