### ISSUE TITLE
QR code doesn't render properly with Ubuntu Mono font

### ISSUE THREAD

**Issue by dipanshunagar** [claudiodangelis/qrcp#126] opened 2020-05-01 19:53 UTC
I installed qrcp with [this .deb](https://github.com/claudiodangelis/qrcp/releases/download/0.6.1/qrcp_0.6.1_linux_x86_64.deb) which is the 0.6.1 version x86_64 build.

OS: Kubuntu 18.04
go version: go1.10.4 linux/amd64

Check screenshot for results:
![Screenshot_20200502_011902](https://user-images.githubusercontent.com/10234389/80836997-8a40ef00-8c13-11ea-9ef9-36a25f8bedf4.png)

**Comment by claudiodangelis** [comment] 2020-05-01 19:59
Hello @dipanshunagar, thanks for reporting. Which font are you using in your terminal? Does it work if you change font? Thanks

**Comment by dipanshunagar** [comment] 2020-05-01 20:08
Ah, yes it worked with font the Monospace. Even though my default was also a mono- Ubuntu Mono.
Thanks. Just a suggestion: can there be a way to configure qrcp so that it opens a new window with the qrcode? A simple image might be more robust.

**Comment by claudiodangelis** [comment] 2020-05-01 21:07
@dipanshunagar good to hear it worked with a different font, I will change the title of this issue. Though it's a bit out of scope, I will introduce the ability to print the QR outside the terminal, as a fallback for those edge cases where for some reason the terminal is not able to properly render the QR.

**Comment by claudiodangelis** [comment] 2020-05-02 11:45
Unfortunately I cannot reproduce the issue with Ubuntu Mono, I just tried and _It works on my machine™_.

I will leave this ticket open for a few days hoping to hear from other users.

Thanks

**Closed** 2020-05-06 05:55 UTC
